# q)Importing the numpy package 


In [6]:
import numpy as np
myarr = np.array([1,2,3,4,5])
print(myarr)

ar=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(ar)

[1 2 3 4 5]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Note : Arrays can store elemements of the same type


# Advantages of array in numpy 
Uses less space and its faster in computation 


# q)Lets check the size of an integer type in Python 

In [2]:
import sys 
b  = 18
sys.getsizeof(b)

28

# q) Lets check the size of an empty list in Python

In [29]:
myl = []
sys.getsizeof(myl)


64

# q Lets add an item to the list and check the size 


In [3]:
myl = [1]
sys.getsizeof(myl)

72

## Note : Every item in the list would occupy 8 bytes 

# q)Lets create a list of 100 elements 

In [31]:
myl=list(range(100))
print(myl)
type(myl)
sys.getsizeof(myl)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


1008

# q)Lets now check the size of the entire  list 


In [37]:
size_l = sys.getsizeof((myl[0])*len(myl))
print(size_l)


24


## Note : getsizeof(myl[1]) would give the size of one element of the list in bytes 



# q)Now lets create an array of 100 elements and check the size of the array 


In [30]:
myar = np.arange(100)
print(myar)
sys.getsizeof(myar)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


496

# q)How to find out the count of number of elements in an array


In [33]:
myar.size # Count of number of elements in an array


100

# q)How to find the size (memory occupied) by every item in an array 


In [24]:
print(myar.itemsize)


4


# Now we need to multiple the lenght of the array with the #memory occupied by each array element to get the total 
# memory occupied by the entire array elements. 



In [34]:
size_a =  (myar.size)*(myar.itemsize)
print(size_a)


400


# Now compare how much memory does an array and list occupy (scroll up and compare with that of the list)


# q)How to verify that numpy arrays are faster than the python lists 


In [4]:
import sys
import time
import numpy as np 

def list_add(l1,l2):
 i=0
 for a in l2:
  l1[i]=l1[i]+a
  i=i+1


count = 10000
l1=list(range(count))
l2=list(range(count))

start=time.time()
list_add(l1,l2)
end=time.time()

elapsed = 1000*(end-start)
print("List addition time is ",elapsed)

a1 = np.arange(count)
a2 = np.arange(count)

start=time.time()
a3=a1+a2
end=time.time()

elapsed = 1000*(end-start)
print("Array addition time is ",elapsed)


List addition time is  0.9961128234863281
Array addition time is  0.0


# WAP - In class exe  : Modify the above program to perform a slightly complex operation on a larger data set to observe the time difference. 


# q)Demonstration of arithmatic operations on arrays 

Adding 2 arrays, 
Subrtacting 2 arrays 
Mul 
Div 


# q)Creating a 2 dimensional array 


In [ ]:
import numpy as np 
a = np.array([[1,2],[3,4]])
print(a)
a.ndim #The ndim will print the dimensionality of the array i.e 1 dimentional or 2 dimensional 


# q)How to count the number of elements in any array 


In [ ]:
print(a.size) 
print("shape =",a.shape) # would print how many rows and cols are there in the array 



# q) Lets see another example of using the shape function

In [4]:
a=np.array([[1,2],[3,4],[5,6]])
a.shape

(3, 2)

# q)Reshaping an array 


In [5]:
b = a.reshape((2,3))
b.shape
print(b)


[[1 2 3]
 [4 5 6]]


# q)Creating a zero value array 


In [6]:
a = np.zeros( (2,3) )   #will result in creating a 2 row and 3 col array, filled with zeroes 
print(a)

b = np.ones((2,3)) #This will create an array with value 1's 
print(b)


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


# q)Using the arange function to create arrays 


In [7]:
a = np.arange(5)
print(a)


[0 1 2 3 4]


# q) Understanding the ravel function,its used to convert an N dimensional array into a 1 dimensional array 


In [8]:
a = b.ravel()
print(a)
type(a)

[1. 1. 1. 1. 1. 1.]


numpy.ndarray

# q)Finding out the min and max element from an array 


In [9]:
b.min()
b.max()

# Note: try the built in function b.sum()


1.0

# WAP In-class exe : To develop a custom user defined function to find out the min and max element from an 2 by 3 array or elements 
# as shown below 
1 2
3 4
5 6 



Hint : U may use the ravel function to flatten it out and then work on finding the min and max elements from the array 
Note : U are not supposed to use the min or max built in function 


In [6]:
import numpy as np
a=np.array([[1,2],[13,4]])
z=a.ravel()
z.sort()
print(type(z))
print("Max:",z[z.size-1],"Min:",z[0])


<class 'numpy.ndarray'>
Max: 13 Min: 1


# q)Operations on arrays (Addition, subtraction and multiplication is possible)


In [31]:
a=np.ones((2,2))
b=np.ones((2,2))
print(a)
print(b)
c = a+b
d = a-b
e = a*b
print("addition result follows\n\n:",c)
print("subtraction result follows\n \n :",d)
print("multiplication result follows\n \n :",e)


[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]
addition result follows

: [[2. 2.]
 [2. 2.]]
subtraction result follows
 
 : [[0. 0.]
 [0. 0.]]
multiplication result follows
 
 : [[1. 1.]
 [1. 1.]]


# Slicing python lists 


In [32]:
l = [1,2,3,4,5]
l[2:4]


[3, 4]

# Similar kind of slicing is possible on Python arrays 


In [33]:
d2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(d2)

print(d2[0,0]) #This would print the element from 0th row and 0th column i.e 1 
print(d2[1,1]) #This would print the element from 0th row and 0th column i.e 5 


[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
5


# 1 2 3
# 4 5 6
# 7 8 9
# q)How to interpret the below statement with respect to the above 3 by 3 array



In [34]:
print(d2[0:2,2]) #would print [3 6] 
# [0:2,2] would translate to [(0,1),2] i.e to print the row 0 and row 1 elements of column 2 which is 3,6


[3 6]


In [38]:
print(d2[:,0:2]) # Print all the row elements from col 0 and col 1


[[1 2]
 [4 5]
 [7 8]]


# q)Iterating the array using for loops 

1 2 3
4 5 6
7 8 9

The array d2 contains the above elements

In [35]:
for row in d2:
 print(row) 


[1 2 3]
[4 5 6]
[7 8 9]


# q)Conditional statements on arrays 


In [37]:
ca = np.arange(9).reshape(3,3)
print("The original array is \n" ,ca)

con = ca > 5 

print(" \nThe boolean array after the conditional statement is applied \n")
print(con)

ca[con] # The boolean TRUE/FALSE array is now the index and print only the numbers satisfying the the > 5 condition 


The original array is 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
 
The boolean array after the conditional statement is applied 

[[False False False]
 [False False False]
 [ True  True  True]]


array([6, 7, 8])

# In class - exe WAP : To create an array with 100 elements (M,N is 10,10) and filter only those elements between than 75 and 100 and create a new array with 5 rows and 5 cols 


In [53]:
import numpy as n
ar=n.array(range(1,101)).reshape(10,10)
l1=list()
s=ar.shape
for i in range(s[0]):
    for j in range(s[0]):
        if(ar[i,j]>75 and ar[i,j]<=100):
            l1.append(ar[i,j])
        
print(l1)
a1=np.array(l1).reshape(5,5)
print(a1)

[76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100]
[[ 76  77  78  79  80]
 [ 81  82  83  84  85]
 [ 86  87  88  89  90]
 [ 91  92  93  94  95]
 [ 96  97  98  99 100]]


# q)Replacing all the elements of an array which is greater than 4 with zero 


In [36]:
ca = np.arange(9).reshape(3,3)
print("The original array is : \n", ca)

con = ca > 4
ca[con]=0
print("\n",ca) 



The original array is : 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

 [[0 1 2]
 [3 4 0]
 [0 0 0]]


# q)Taking a 1 dimensional array and reshaping it to a 2 dimensional array 


In [8]:
newa = np.arange(10).reshape(2,5)
newb = np.arange(10,20).reshape(2,5)

print(newa)
print(newb)



[[0 1 2 3 4]
 [5 6 7 8 9]]
[[10 11 12 13 14]
 [15 16 17 18 19]]


# understanding stacking operations on an array 


In [10]:
newc=np.vstack((newa,newb))  # vstack is for vertical stacking and similarly hstack can be used too

print(newc)
type(newc)
newc=np.hstack((newa,newb))  # vstack is for vertical stacking and similarly hstack can be used too
print(newc)
type(newc)



[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 0  1  2  3  4 10 11 12 13 14]
 [ 5  6  7  8  9 15 16 17 18 19]]


numpy.ndarray

# q)We can split a large arrays into smaller arrays 


In [13]:
biga = np.arange(60).reshape(6,10)
print(biga)
biga.shape

sma = np.hsplit(biga,2)  #  sma is a list consisting of 2 smaller arrays 
print(sma[0])
print(sma[1])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]
 [50 51 52 53 54]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]
 [45 46 47 48 49]
 [55 56 57 58 59]]


# WAP : Demonstrate a code snippet to split the above biga into 3 smaller arrays using vsplit


In [85]:
biga = np.arange(60).reshape(6,10)
print(biga)
a=biga.shape
print(biga.shape)

sma = np.vsplit(biga,3)  #  sma is a list consisting of 3 smaller arrays 
print(sma[0])
print(sma[1])
print(sma[2])



[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]
(6, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]]


# Suppose you have array of 4 rows and 4 cols like the one shown below 
1 2 3 4
5 6 7 8
9 10 11 12
13 14 15 16

# In class lab exe - WAP : to print only the right diagonal elements i.e 1, 6, 11, 16 
Hint : U need to use loops 


In [92]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
size=a.shape
for i in range(size[0]):
    for j in range(size[0]):
        if(i==j):
            print(a[i,j])
        

1
6
11
16


# In class lab WAP : Modify the above program to print the left diagonal elements i.e 4,7,10,13


In [94]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
size=a.shape
for i in range(size[0]):
    for j in range(size[0]):
        if(i+j==size[0]-1):
            print(a[i,j])
        
        

4
7
10
13


# In class lab : WAP : To take N elments into a function, the function must be able to generate a zero array of an appropriate dimension and populate the N elements as the right diagonal elements of the array. 


In [14]:
import numpy as np

n1=input()
n=n1.split(",")

def fun1(n):
    l=len(n)
    ar=np.zeros((l,l))
    for i in range(l):
        ar[i][i]=n[i]
    print(ar)
    
fun1(n)

1,2,3,4,5
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]]


# *************Take home weekend group assignmet************
WAP to solve the below sudoku 

0 4 0 1
3 0 4 0
1 0 0 4
0 2 1 0 

The zero's represent empty cells. 



Note : Do not use the readily available algorithms to solve the sudoku problems. Instead, develop your custom code to solve only the above problem. Each group should choose a different sudoku problem which is at least 4 by 4 and above.   

 



In [56]:
import numpy as np
ar=np.array([[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]])
print(ar)

[[0 4 0 1]
 [3 0 4 0]
 [1 0 0 4]
 [0 2 1 0]]


In [10]:
def findNextCellToFill(grid, i, j):
            for x in range(0,4):
                    for y in range(0,4):
                            if grid[x][y] == 0:
                                    return x,y 
            return -1,-1

def isValid(grid, i, j, e):
            rowOk=all([e!=grid[i][x] for x in range(4)])
            if rowOk:
                columnOk = all([e!=grid[x][j] for x in range(4)])
                if columnOk:
                            X,Y=2*(i//2),2*(j//2) 
                            for x in range(X,X+2):
                                    for y in range(Y,Y+2):
                                            if grid[x][y]==e:
                                                    return False
                            return True
            return False
        
def solveSudoku(grid, i=0, j=0):
            i,j = findNextCellToFill(grid, i, j)
            if i==-1:
                return True
            for val in range(1,5):
                if isValid(grid,i,j,val):
                    grid[i][j]=val   
                    if solveSudoku(grid, i, j):
                        return True
                    grid[i][j]=0
            return False
        
        
input1=[[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]]
solveSudoku(input1)
print(input1)


[[2, 4, 3, 1], [3, 1, 4, 2], [1, 3, 2, 4], [4, 2, 1, 3]]


In [20]:

def findNextCellToFill(grid,n, i, j):
            for x in range(0,n):
                    for y in range(0,n):
                            if grid[x][y] == 0:
                                    return x,y 
            return -1,-1

def isValid(grid,n, i, j, e):
            rowOk=all([e!=grid[i][x] for x in range(n)])
            if rowOk:
                columnOk = all([e!=grid[x][j] for x in range(n)])
                if columnOk:
                            X,Y=2*(i//(n//2)),2*(j//(n//2)) 
                            for x in range(X,X+(n//2)):
                                    for y in range(Y,Y+(n//2)):
                                            if grid[x][y]==e:
                                                    return False
                            return True
            return False
        
def solveSudoku(grid, n, i=0, j=0):
            i,j = findNextCellToFill(grid,n, i, j)
            if i==-1:
                return True
            for val in range(1,n+1):
                if isValid(grid,n, i,j,val):
                    grid[i][j]=val   
                    if solveSudoku(grid,n, i, j):
                        return True
                    grid[i][j]=0
            return False
        
n=int(input("Enter the Value for N:"))      
#input1=[[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]]
input2=[[0,0,0,2,6,0,7,0,1],[6,8,0,0,7,0,0,9,0],[1,9,0,0,0,4,5,0,0],[8,2,0,1,0,0,0,4,0],[0,0,4,6,0,2,9,0,0],[0,0,5,0,0,0,3,0,2,8],[0,0,9,3,0,0,0,7,4],[0,4,0,0,5,0,0,3,6],[7,0,3,0,1,8,0,0,0]]

#solveSudoku(input1, n)
solveSudoku(input2, n)
print(input1)
print(input2)



Enter the Value for N:9
[[0, 4, 0, 1], [3, 0, 4, 0], [1, 0, 0, 4], [0, 2, 1, 0]]
[[0, 0, 0, 2, 6, 0, 7, 0, 1], [6, 8, 0, 0, 7, 0, 0, 9, 0], [1, 9, 0, 0, 0, 4, 5, 0, 0], [8, 2, 0, 1, 0, 0, 0, 4, 0], [0, 0, 4, 6, 0, 2, 9, 0, 0], [0, 0, 5, 0, 0, 0, 3, 0, 2, 8], [0, 0, 9, 3, 0, 0, 0, 7, 4], [0, 4, 0, 0, 5, 0, 0, 3, 6], [7, 0, 3, 0, 1, 8, 0, 0, 0]]


In [21]:
def findNextCellToFill(grid, i, j):
            for x in range(0,4):
                    for y in range(0,4):
                            if grid[x][y] == 0:
                                    return x,y 
            '''for x in range(i,4):
                    for y in range(j,4):
                            if grid[x][y] == 0:
                                    return x,y   
                                              '''
            return -1,-1

def isValid(grid, i, j, e):
            rowOk = all([e != grid[i][x] for x in range(4)])
            if rowOk:
                    columnOk = all([e != grid[x][j] for x in range(4)])
                    if columnOk:
                            # finding the top left x,y co-ordinates of the section containing the i,j cell
                            secTopX, secTopY = 2 *(i//2), 2 *(j//2) #floored quotient should be used here. 
                            for x in range(secTopX, secTopX+2):
                                    for y in range(secTopY, secTopY+2):
                                            if grid[x][y] == e:
                                                    return False
                            return True
            return False
        
def solveSudoku(grid, i=0, j=0):
            i,j = findNextCellToFill(grid, i, j)
            if i==-1:
                return True
            for val in range(1,5):
                if isValid(grid,i,j,val):
                    grid[i][j]=val   
                    if solveSudoku(grid, i, j):
                        return True
                    grid[i][j] = 0
            return False
        
        
input1=[[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]]
solveSudoku(input1)
print(input1)


[[2, 4, 3, 1], [3, 1, 4, 2], [1, 3, 2, 4], [4, 2, 1, 3]]


# Python Practice

In [3]:
def countingValleys(n, s):
        k=[1]
        p=0
        count=0
        for i in range(n):
            if s[i]=='U':
                p=p+1

            elif s[i]=='D':
                p=p-1
            if p==0 and s[i]=='U':
                  count=count+1
        return  count

n = int(input())
s = input()

result = countingValleys(n, s)
result

10
UDUUUDUDDD


0

In [ ]:
import math
import os
import random
import re
import sys


# Complete the sockMerchant function below.
def sockMerchant(n, ar):
        sum1=0
        a=[0]
        for i in range(n):
            if ar.count(ar[i])!= 1:
                if not(ar[i]in a):
                    sum1 += (ar.count(ar[i])//2)
                    a.append(ar[i])
        return sum1
            

n = int(input())

ar = list(map(int, input().rstrip().split()))

result = sockMerchant(n, ar)


result

In [9]:
def jumpingOnClouds(c):
    count = 0
    i = 0

    while (True):
            if ((i+2) < len(c) and c[i + 2] == 0):
                 i=i+2
            elif ((i+1) < len(c)):
                i=i+1
            else:
                break
            count=count+1
    return count
    

n = int(input())
c = list(map(int, input().rstrip().split()))
result = jumpingOnClouds(c)
result

7
0 0 1 0 0 1 0


3

1

In [2]:
def repeatedString(s, n):
    return (s.count("a") * (n// len(s))) + s[:n % len(s)].count("a")

s = input()
n = int(input())
result = repeatedString(s, n)
result


aba
10


7

In [ ]:
import numpy as np
from scipy import stats

size = int(input())
numbers = list(map(int, input().split()))
print(np.mean(numbers))
print(np.median(numbers))
print(int(stats.mode(numbers)[0]))