In [1]:
import numpy as np
ar1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar1)
print(ar1.sum(0)) # sum of all cols
print(ar1.sum(1)) # sum of all rows


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[12 15 18]
[ 6 15 24]


In [34]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
ar1=np.arange(11)

slice1=ar1[2:7]                     # WON'T CREATE A COPY BUT A REFERENCE 
print(slice1)
print(type(slice1))
slice1[:]=99
print(slice1)
print(ar1)                           # values inside original array is also changed



[2 3 4 5 6]
<class 'numpy.ndarray'>
[99 99 99 99 99]
[ 0  1 99 99 99 99 99  7  8  9 10]


In [27]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
ar1=np.arange(1,10).reshape(3,3)
print(ar1)
print(ar1[1:,1:])         #ar[rows,cols]  
print(ar1[1:,:2])
print(ar1[:2,1:])


[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[5 6]
 [8 9]]
[[4 5]
 [7 8]]
[[2 3]
 [5 6]]


In [38]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
ar1=np.arange(11)
slice1=ar1[2:7].copy()            # making a copy of the orignal array
print(slice1)
print(type(slice1))
slice1[:]=99
print(slice1)
print(ar1)    

[2 3 4 5 6]
<class 'numpy.ndarray'>
[99 99 99 99 99]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [67]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
ar1=np.zeros([10,10])
print(ar1)
for i in range(len(ar1)):
    ar1[i]=i
    
print(ar1)



    

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]


In [63]:
for k in range(len(ar1)):             
    ar1[:,k]=k
    
print(ar1)
print(ar1.T)                      # Transpose

ar3=ar1.dot(ar1.T)
print(ar3)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6. 6. 6. 6. 6. 6.]
 [7. 7. 7. 7. 7. 7. 7. 7. 7. 7.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [9. 9. 9. 9. 9. 9. 9. 9. 9. 9.]]
[[285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285

In [62]:
ar2=np.dot(ar1,ar1.T)
print(ar2)

[[285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]
 [285. 285. 285. 285. 285. 285. 285. 285. 285. 285.]]


In [71]:

ar1[[2,4,6]]  # get the values of 2nd, 4th, 6th row

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [82]:
ar=np.arange(18).reshape(3,2,3)     #(slices,rows,cols)
print(ar)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]]]


In [92]:
from numpy.random import randn
arr5=randn(6)
print(arr5)                        # get a values between -3 and 3

[ 0.68476842 -0.45847477 -0.15302549 -2.50779562 -1.64039634  0.78411239]


In [107]:
from numpy.random import randint
arr6=randint(1,51,5)             # (start,end,size of array)
print(arr6)

[ 2 35  9  8 25]


In [108]:
c=np.array([True,False,True])
print(c)

[ True False  True]


In [111]:
a=np.array([1,2,3])
b=np.array([10,20,30])
print(a,b)

np.where(c,a,b)           #will print the values from a if it is true else from b if false

[1 2 3] [10 20 30]


array([ 1, 20,  3])

In [115]:
c=np.array([[True,False],[True,False]])
print(c)
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
np.where(c,a,b)

[[ True False]
 [ True False]]


array([[ 1, 20],
       [ 3, 40]])

In [116]:
c=np.array([[True,False],[True,False]])
print(c)
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
np.where(c,b,a)

[[ True False]
 [ True False]]


array([[10,  2],
       [30,  4]])

In [120]:

a=np.arange(1,10).reshape(3,3)
print(a)
print(np.where(a<5))
print(np.where(a>5))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(array([0, 0, 0, 1], dtype=int64), array([0, 1, 2, 0], dtype=int64))
(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))


In [126]:
ar2=np.array(['bng','chn','mum','pun','bng'])
print(np.unique(ar2))

['bng' 'chn' 'mum' 'pun']


In [135]:
ar2=np.arange(1,5)
np.save('myarray',ar2)
ar3=np.load('myarray.npy')
print(ar3)
np.savetxt('myarraytxt.txt',ar2)
ar4=np.loadtxt('myarraytxt.txt')
print(ar4)

[1 2 3 4]
[1. 2. 3. 4.]


In [136]:
ar4=np.loadtxt('myarraytxt.txt')    # after changing the value in the txt file
print(ar4)

[ 1.  2.  3. 44.]


In [142]:
c=np.array([[True,False],[True,False]])

print(c.any())        # if any value is true in c then it will return true
print(c.all())        # if any value is false in c then it will return false


True
False


In [157]:
a=np.array([1,2,np.nan])
print(a)
print(a[2])                                # nan is null vlaue in numpy
np.isnan(a)


[ 1.  2. nan]
nan


array([False, False,  True])

In [161]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
ser1=Series([1,2,3])                         # stored as the array      
print(ser1)

0    1
1    2
2    3
dtype: int64


In [160]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame
ser1=Series(['a','b','c'])            # stored as the array
print(ser1)


0    a
1    b
2    c
dtype: object


In [184]:
ser1=Series([1,2,3,4],index=['a','b','c','a'])            # stored as the array
print(ser1)
print(ser1['a'])
print(ser1[0])
print(ser1.index)             # shows all keys
print(ser1.values)            # shoes all values

a    1
b    2
c    3
a    4
dtype: int64
a    1
a    4
dtype: int64
1
Index(['a', 'b', 'c', 'a'], dtype='object')
[1 2 3 4]


In [364]:
ser1=Series({'a':1,'b':2,'c':3})                  # using a dictionary
print(ser1[0])
print(ser1)
print(ser1.values)

1
a    1
b    2
c    3
dtype: int64
[1 2 3]


In [174]:
ser1=Series({'a':'Jithin','b':'bng','c':'series'})                  # using a dictionary
print(ser1)
print(ser1.values)

a    Jithin
b       bng
c    series
dtype: object
['Jithin' 'bng' 'series']


# Selecting Entries
Grab by index 
Grab by Logic



In [183]:
ser1[ser1>1] # Gives a series


b    2
c    3
dtype: int64

In [185]:
ser1>1    # gives Boolean

a    False
b     True
c     True
a     True
dtype: bool

In [366]:
ser1=Series({'a':1,'b':2,'c':3})   
dict1=dict(ser1)
print(dict1)

{'a': 1, 'b': 2, 'c': 3}


In [189]:
a1=Series(dict1)
print(a1)

a    1
b    2
c    3
dtype: int64


In [207]:
ser1=Series({'a':1,'b':2,'c':3})   
l1=['a','b','c','d']
dict1=ser1.to_dict()     # to convert to a dictionary
print(dict1)
s1=Series(dict1,l1)
print(s1)
print(s1.isnull())
print(s1.notnull())
ser1.name="Series1"
print(ser1.name)

{'a': 1, 'b': 2, 'c': 3}
a    1.0
b    2.0
c    3.0
d    NaN
dtype: float64
a    False
b    False
c    False
d     True
dtype: bool
a     True
b     True
c     True
d    False
dtype: bool
Series1


In [213]:
ser1.index.name="alphabets"             # providing the title for indexes

print(ser1)
print(ser1*4)

alphabets
a     4
b     8
c    12
Name: Series1, dtype: int64
alphabets
a    1
b    2
c    3
Name: Series1, dtype: int64


In [227]:
dict1 = DataFrame(np.arange(9).reshape(3,3))
dict1

0  1  2
0  0  1  2
1  3  4  5
2  6  7  8

In [226]:
dframe1 = DataFrame(np.arange(9).reshape(3,3),index=['a','b','c'],columns=['col1','col2','col3'])
dict1    # will show index for rows and columns

col1  col2  col3
a     0     1     2
b     3     4     5
c     6     7     8

In [234]:
dframe2 = DataFrame({'Alpha':['one','two','Three'],'Name':[1,2,3]})
dframe2

Alpha  Name
0    one     1
1    two     2
2  Three     3

In [369]:
dframe2 = DataFrame({'Company':['Facebook','Google','Microsoft'],'Price':[1000,2000,3000],'Ticker':['FB','GOOG','MIC']},index=['a','b','c'])
dframe2

Company  Price Ticker
a   Facebook   1000     FB
b     Google   2000   GOOG
c  Microsoft   3000    MIC

In [370]:
dframe2['Company']





a     Facebook
b       Google
c    Microsoft
Name: Company, dtype: object

In [371]:
dframe2.iloc[0]

Company    Facebook
Price          1000
Ticker           FB
Name: a, dtype: object

In [373]:
dframe2.loc['a'] #[created index]


Company    Facebook
Price          1000
Ticker           FB
Name: a, dtype: object

In [266]:
dframe2.loc['a']  # [value of the index created by us]


Company    Facebook
Price          1000
Ticker           FB
Name: a, dtype: object

In [271]:
dframe2['Dprice']=[999,1999,2999]
dframe2

Company  Price Ticker  Dprice
a   Facebook   1000     FB     999
b     Google   2000   GOOG    1999
c  Microsoft   3000    MIC    2999

In [283]:
dframe2['Dprice']=dframe2['Price']*0.1
dframe2

Company  Price Ticker  Dprice
a   Facebook   1000     FB   100.0
b     Google   2000   GOOG   200.0
c  Microsoft   3000    MIC   300.0

In [284]:
del(dframe2['Dprice'])


In [290]:
dframe2

Company  Price Ticker
a   Facebook   1000     FB
b     Google   2000   GOOG
c  Microsoft   3000    MIC

In [298]:
dframe2.drop('a')   # doesnot make the changes in the original 
dframe2

Company  Price Ticker
a   Facebook   1000     FB
b     Google   2000   GOOG
c  Microsoft   3000    MIC

In [299]:
dframe2.drop('a',inplace=True)  # makes changes in the original frame
dframe2

Company  Price Ticker
b     Google   2000   GOOG
c  Microsoft   3000    MIC

In [300]:
dframe2.T

b          c
Company  Google  Microsoft
Price      2000       3000
Ticker     GOOG        MIC

In [303]:
dframe2.columns    # to show the cols in Dataframe


Index(['Company', 'Price', 'Ticker'], dtype='object')

In [304]:
dframe2.index

Index(['b', 'c'], dtype='object')

In [320]:
dframe3=DataFrame(['India','Pakistan','Bangaldesh'],index=[0,4,10])
dframe3.reindex(np.arange(15),method='ffill')       # forward fill        # works for data frame and series


0
0        India
1        India
2        India
3        India
4     Pakistan
5     Pakistan
6     Pakistan
7     Pakistan
8     Pakistan
9     Pakistan
10  Bangaldesh
11  Bangaldesh
12  Bangaldesh
13  Bangaldesh
14  Bangaldesh

In [321]:
ser3=Series(['India','Pakistan','Bangladesh'],index=[0,4,10])   # works for data frame and series
print(ser3)
dframe3.reindex(np.arange(15),method='ffill')   

0          India
4       Pakistan
10    Bangladesh
dtype: object


0
0        India
1        India
2        India
3        India
4     Pakistan
5     Pakistan
6     Pakistan
7     Pakistan
8     Pakistan
9     Pakistan
10  Bangaldesh
11  Bangaldesh
12  Bangaldesh
13  Bangaldesh
14  Bangaldesh

In [322]:
dframe3.reindex(np.arange(15),method='bfill')     # backward fill

0
0        India
1     Pakistan
2     Pakistan
3     Pakistan
4     Pakistan
5   Bangaldesh
6   Bangaldesh
7   Bangaldesh
8   Bangaldesh
9   Bangaldesh
10  Bangaldesh
11         NaN
12         NaN
13         NaN
14         NaN

# Write code to print a dictionary where the keys are numbers between 1 and 15 (both included) and the values are square of keys.
#Sample Dictionary {1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}

In [327]:
l1 = range(1,16)
d = dict((i,i*i) for i in l1) 
print(d)
type(d)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100, 11: 121, 12: 144, 13: 169, 14: 196, 15: 225}


dict

In [356]:
ser2= Series([1,2,3],index=('b','c','d'))
print(ser2)
# reindexed series 
rser2 = ser2.reindex(index=['a','b','c','d'],fill_value=0)   
print(rser2)
        

b    1
c    2
d    3
dtype: int64
a    0
b    1
c    2
d    3
dtype: int64


In [2]:
import seaborn as sns


In [3]:
sns.get_dataset_names()

C:\Users\lenovo\Anaconda3\lib\site-packages\seaborn\utils.py:376: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("lxml"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 376 of the file C:\Users\lenovo\Anaconda3\lib\site-packages\seaborn\utils.py. To get rid of this warning, pass the additional argument 'features="lxml"' to the BeautifulSoup constructor.

  gh_list = BeautifulSoup(http)


['anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'iris',
 'mpg',
 'planets',
 'tips',
 'titanic']

In [6]:
tips=sns.load_dataset("tips")
tips.head()


total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [7]:
tips.tail()

total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [8]:
tips.describe()    # works only on Numercial Data

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [9]:
tips.info()    # we can use it to check null values

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null category
smoker        244 non-null category
day           244 non-null category
time          244 non-null category
size          244 non-null int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.2 KB


In [10]:
tips.nunique()

total_bill    229
tip           123
sex             2
smoker          2
day             4
time            2
size            6
dtype: int64