In [1]:
a=10
print(a)

10


In [2]:
#Title



In [3]:
print("Hello")


Hello


In [1]:
print(5,4)

5 4


In [4]:
print('''1
2
3''')

1
2
3


In [3]:
print("1
      2
      3")

SyntaxError: EOL while scanning string literal (<ipython-input-3-224cf3b7d303>, line 1)

In [5]:
'''
m
l
o
p
'''

'\nm\nl\no\np\n'

In [6]:
'''
line1
line2
'''

'\nline1\nline2\n'

In [7]:
print('m'+'n')

mn


In [8]:
print(5/3)

1.6666666666666667


In [9]:
print(5//3)

1


In [1]:
floor(1/2)

NameError: name 'floor' is not defined

In [11]:
floor(0.5)

NameError: name 'floor' is not defined

In [3]:
a=str(a)
print(a)

asd


In [2]:
a="asd"
print(a)

asd


In [3]:
type(a)

str

In [4]:
print('a')

a


In [5]:
print(str(a))

asd


In [6]:
print(2 + 2)
print(50 - 5*6)
print((50 - 5*6) / 4)
print(8 / 5) # division always returns a floating point number

4
20
5.0
1.6


In [10]:
b=2/3
print(b)
type(b)
a=2//3
print(a)
type(a)

0.6666666666666666
0


int

In [8]:
type(a)

int

In [11]:
b=2/3
print(b)
type(b)

0.6666666666666666


float

In [4]:
print=10
print("hello")

TypeError: 'int' object is not callable

In [13]:
print(print)

TypeError: 'int' object is not callable

In [5]:
del(print)

In [6]:
print('hello')

hello


In [7]:
a==10
print(a)

asd


In [8]:
del(a)

In [9]:
print(a)

NameError: name 'a' is not defined

In [19]:
a==10
print(a)

NameError: name 'a' is not defined

In [20]:
a=10
print(a)

10


In [21]:
a=10
b=10
a==b

True

##### a=10
b=10
if(a==b):
    print("true")
else:
    print("False")

In [23]:
type(true)

NameError: name 'true' is not defined

In [24]:
type(True)

bool

In [25]:
a=10
b=10
a>b

False

In [26]:
a=10
b=10
a<b

False

In [27]:
10<age>5

NameError: name 'age' is not defined

In [28]:
age=7
10<age>5

False

In [29]:
age=7
10>age<5

False

In [30]:
age=7
10>age>5

True

In [31]:
print("it\'s'")

it's'


In [32]:
print("it\'s")

it's


In [33]:
print("it's")

it's


In [34]:
a='hello world'
len.a()

AttributeError: 'builtin_function_or_method' object has no attribute 'a'

In [35]:
len(a)


11

In [1]:
tv_brand='samsung'
tv_price=10000
string1="tv=%s,price=%d"%(tv_brand,tv_price)
print(string1)
print("tv=%s,price=%d"%(tv_brand,tv_price))

tv=samsung,price=10000
tv=samsung,price=10000


In [43]:
h='Hello'
print(h)

Hello


In [3]:
tv_brand='samsung'
tv_price=10000
string1="tv=%s,price=%0.5f"%(tv_brand,tv_price)
print(string1)

tv=samsung,price=10000.00000


In [10]:
string1 = "Data Analytics" # string1 is a variable of the type string

print(len(string1))
print(string1[::-1])

14
scitylanA ataD


In [17]:
print(string1[::-1])

scitylanA ataD


In [55]:
print(string1[0:4])

Data


In [57]:
print(string1[0:])

Data Analytics


In [60]:
print(string1[0:14:2])

Dt nltc


In [61]:
print(string1[0::2])

Dt nltc


In [5]:
print(string1[-1:-14:-2])

siyaAaa


In [72]:
a=100
print("%x"%(a))
print(hex(a))

64
0x64


0x64


In [66]:
print(bin(a))

0b1100100


In [68]:
print("%o"%(a))

144


In [74]:
print(oct(a))

0o144


In [79]:
string1[0]="a"
print(string1)

TypeError: 'str' object does not support item assignment

In [15]:
print(string1.find("analytics"))
d=string1.find("d")
d

-1


-1

In [16]:
st="samsung=1000"
res=st.find("samsung=")
print(st.find('s'))
print(st[res+len("samsung="):])

0
1000


In [98]:
string1.split()

['Data', 'Analytics']

In [100]:
mylist = ["Ram",10,90.12,True] # A list can have both strings and numbers
print(mylist)
type(mylist)

['Ram', 10, 90.12, True]


list

In [101]:
mylist[0]

'Ram'

In [102]:
mylist[1]

10

In [119]:
mylist[-1:-4:-1]

[True, 90.12, 10]

In [104]:
mylist[1:3]

[10, 90.12]

In [112]:
string1[-1:-13:-2]

'siyaAa'

In [120]:
mylist[0]='Jithin'

In [121]:
print(mylist)

['Jithin', 10, 90.12, True]


In [16]:
mylist2=['joy',10,12.9]
mylist=["Ram",10,90.12,True]
mylist.append(mylist2)
print(mylist)
print(mylist[4][2])

['Ram', 10, 90.12, True, ['joy', 10, 12.9]]
12.9


In [15]:
print(mylist[4][0])
type(mylist[4])

joy


list

In [11]:
qwe="ajay vijay anil"
list1=qwe.split(" ")
print(list1)

['ajay', 'vijay', 'anil']


In [20]:
list1=[10,100,3,5,15]
list2=list1.copy()
list1[0]="hello"
print(list1,list2)


['hello', 100, 3, 5, 15] [10, 100, 3, 5, 15]


In [20]:
tup=(20,)
type(tup)
print(tup)

(20,)


In [18]:
tup=("string")
type(tup)

str

In [21]:
list1=[1]
type(list1)

list

In [32]:
a=10.12345
print("%f"%a)


10.123450


In [26]:
string="bangalore express"
print(string.split(" "))
print(type(string))
print(string.partition(" "))
print(type(string))
print(string.title().center(30).find("Bangalore"))




['bangalore', 'express']
<class 'str'>
('bangalore', ' ', 'express')
<class 'str'>
6


In [24]:
tup1=(1,2,3,4)
list1=list(tup1)
list1[0]=100
print(tuple(list1))

(100, 2, 3, 4)


In [78]:
dict1={"Name":"Jithin","Age":23,"Marks":100}

In [79]:
print(dict1)

{'Name': 'Jithin', 'Age': 23, 'Marks': 100}


In [81]:
dict1["Name"]

'Jithin'

In [89]:
dict2={"Mobile":{"screen":5,"color":"Red","hardware":{"CPU":1.8,"cache":[128,256]}}}

In [92]:
dict2["Mobile"]["hardware"]["cache"][0]

128

In [93]:
dict2.items()

dict_items([('Mobile', {'screen': 5, 'color': 'Red', 'hardware': {'CPU': 1.8, 'cache': [128, 256]}})])

In [99]:
dict2["Mobile"]= {"screen":7,"color":"Red","hardware":{"CPU":1.8,"cache":[128,256]}}
print(dict2)

{'Mobile': {'screen': 7, 'color': 'Red', 'hardware': {'CPU': 1.8, 'cache': [128, 256]}}}


In [105]:
i=5
if(i>=10):
    print("i greater than 10")
else:
    print("i less than 10")

i less than 10


In [107]:
i=5
if(i>10):
    print("i greater than 10")
elif(i<=5):
    print("i less than 10")
else:
    print("Error")

i less than 10


In [117]:
year=input("Year?")
year=int(year)
if((year%4)==0):
    print("Leap Year")
else:
    print("not a leap year ")


Year?2018
not a leap year 


In [122]:
age=input("Enter the age :")
age=int(age)
if(0<age<5):
    print("No")
elif(10>age>4):
    print("Half")
elif(60>age>9):
    print("Full")
else:
    print("senior")

Enter the age :80
senior


In [4]:
mark=int(input("Enter the marks:"))
#mark=int(marks)
if(0<mark<36):
    print("Pass")
elif(35<mark<50):
    print("Third")
elif(50<mark<61):
    print("Second")
else:
    print("First")

Enter the marks:85
First


In [17]:
string="bangalore express"
print(string)
print(string.partition(" "))
type(string)

bangalore express
('bangalore', ' ', 'express')


str

In [32]:
a = 10
if ( a == 10 ) : 
    print("Value of a is ",a)
else : 
    print("Value of a is ",a)

Value of a is  10


In [33]:
l1 = [1,2,3,4]
l1.append(5)
print(l1)


[1, 2, 3, 4, 5]


In [34]:
l1.pop()

5

In [35]:
l1.pop(2)

3

In [36]:
l1


[1, 2, 4]

In [37]:
l1.pop()

4

In [43]:
list1=[(1,2,3,[1,2,3]),(4,5,6)]
print(list1)


[(1, 2, 3, [1, 2, 3]), (4, 5, 6)]


In [46]:
list1[0][3][0]=100
print(list1)

[(1, 2, 3, [100, 2, 3]), (4, 5, 6)]


In [47]:
a=100
b=int(a/3)
print(b)

33


In [ ]:

list1=[1,2]
val= int(input("Enter  the year"))
list1.append(val)
list1.extend(val)
if(val%4==0):
    print("Leap year")
else:
    print("not leap year")


In [50]:

list1=[1,2]
list2=[2,3]
list1.extend(list2)
print(list1)
list1.append(list2)
print(list1)

[1, 2, 2, 3]
[1, 2, 2, 3, [2, 3]]


In [2]:
n=7
if(n % 2 != 0 )and(n % 3 !=0)and(n % 4 !=0)and(n % 5 !=0)and(n % 6 != 0):
    print("Is a Prime Number")
else:
    print("Not a Prime Number")   


Is a Prime Number


In [8]:
list1=[1,2,3]
if 1 in list1:
    print("True")
else:
    print("False")

True


In [9]:
s="Hello"
if "He" in s:
    print("Yes")
else:
    print("No")

Yes


In [2]:
t=(10,4,5,6,7)
b=sorted(t)
print(b) # after sorting b becomes a list
b=tuple(b)
print(b)
type(b)

[4, 5, 6, 7, 10]
(4, 5, 6, 7, 10)


tuple

In [12]:
l=[10,4,5,6,7]
#l.sort() # using member function
b=sorted(l) # after sorting b becomes a list
print(b)
type(b)

[4, 5, 6, 7, 10]


list

In [3]:
mark=int(input("Enter the marks:"))
if(mark<=29):
    print("FF")
elif(30<mark<=39):
    print("DD")
elif(40<mark<=49):
    print("CD")
elif(50<mark<=59):
    print("CC")
elif(60<mark<=69):
    print("BC")
elif(70<mark<=79):
    print("BB")
elif(80<mark<=89):
    print("AB")
else:
    print("AA")


Enter the marks:-1
FF


In [4]:
for name in ["Joe","Zoe","Brad","Angelina","Zuki","Thandi","Paris"]:
    invite = "Hi " + name + ".  Please come to my party on Saturday!"
    print(invite)

Hi Joe.  Please come to my party on Saturday!
Hi Zoe.  Please come to my party on Saturday!
Hi Brad.  Please come to my party on Saturday!
Hi Angelina.  Please come to my party on Saturday!
Hi Zuki.  Please come to my party on Saturday!
Hi Thandi.  Please come to my party on Saturday!
Hi Paris.  Please come to my party on Saturday!


In [7]:
a=["Jithin","James","joe"]
for name in a:
    print(name)


Jithin
James
joe


In [8]:
a="Jithin"
for name in a:
    print(name)


J
i
t
h
i
n


In [8]:
l2=input("Enter the Age:")
l2=l2.split()
print(l2)
for x in l2 :
    val=int(x)
    if (val<5):
        print("No Ticket")
    elif(4<val<15):
        print("Half Ticket")
    elif(50>val>15):
        print("Full Ticket")
    else:
        print("Senior Citizen")

Enter the Age:89 56 10 2
['89', '56', '10', '2']
Senior Citizen
Senior Citizen
Half Ticket
No Ticket


In [11]:
list1=['Hello','100','50']

for i in list1:
    if i.isdigit():
        val=int(i)
        if (val<5):
            print("No Ticket")
        elif(4<val<15):
            print("Half Ticket")
        elif(50>val>15):
            print("Full Ticket")
        else:
            print("Senior Citizen")
    else:
         print("Cannot")

Cannot
Senior Citizen
Senior Citizen


In [4]:
a=int(input("Enter the Number"))
if(a % 2 == 0) :   
    print(a," is even number")


Enter the Number2
2  is even number


In [6]:
a=int(input("Enter the Number:"))
if(a % 2 != 0) :   
    print(a," is not even number")

Enter the Number9
9  is not even number


In [13]:
list1=[10,20]
list1=str(list1)
print(list1)
type(list1)

[10, 20]


str

In [27]:
list1=list(range(0,100,4))
print(list1)

[0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64, 68, 72, 76, 80, 84, 88, 92, 96]


In [29]:
for x in range(1,100,8):
    if (x%2==0):
        print("Even")
    else:
        print("Odd")
        

Odd
Odd
Odd
Odd
Odd
Odd
Odd
Odd
Odd
Odd
Odd
Odd
Odd


In [48]:
str1="Student"
list1=[]
for i in range(1,100,1):
    list1.append(str1+str(i))
    
print(list1)

['Student1', 'Student2', 'Student3', 'Student4', 'Student5', 'Student6', 'Student7', 'Student8', 'Student9', 'Student10', 'Student11', 'Student12', 'Student13', 'Student14', 'Student15', 'Student16', 'Student17', 'Student18', 'Student19', 'Student20', 'Student21', 'Student22', 'Student23', 'Student24', 'Student25', 'Student26', 'Student27', 'Student28', 'Student29', 'Student30', 'Student31', 'Student32', 'Student33', 'Student34', 'Student35', 'Student36', 'Student37', 'Student38', 'Student39', 'Student40', 'Student41', 'Student42', 'Student43', 'Student44', 'Student45', 'Student46', 'Student47', 'Student48', 'Student49', 'Student50', 'Student51', 'Student52', 'Student53', 'Student54', 'Student55', 'Student56', 'Student57', 'Student58', 'Student59', 'Student60', 'Student61', 'Student62', 'Student63', 'Student64', 'Student65', 'Student66', 'Student67', 'Student68', 'Student69', 'Student70', 'Student71', 'Student72', 'Student73', 'Student74', 'Student75', 'Student76', 'Student77', 'Studen

In [58]:
count = 0 
myl = [1,2,3,4,5,6,7,8]
for x in myl: 
    if(x%2==0):
        print(x)
        count=count+1
    if(count==2):
        break 
print("found 2 even numbers")

2
4
found 2 prime numbers


In [55]:
list1=[1,2,"Hello",5,6]
for i in list1:
    if(i!="Hello"):
        print(i)
    else:
        break


1
2


In [83]:
count = 0 
count1 = 4
myl = [1,2,3,4,5,6,7,8]
l1=[]
for x in myl: 
    if(x%2==0):
        l1.append(x)
        count=count+1
    if(count==2):
        break 
print("found 2 even numbers")
for x in myl:
    if(x%2!=0):
        count1=count1-1
    if(count1<2 and x%2!=0):
        l1.append(x)
    if(count1==0):
        break
print("found 2 odd numbers")
print(l1)

found 2 even numbers
found 2 odd numbers
[2, 4, 5, 7]


In [84]:
count1 = 4
myl = [1,2,3,4,5,6,7,8]
for x in myl:
    if(x%2!=0):
        count1=count1-1
    if(count1<2 and x%2!=0):
        print(x)
    if(count1==0):
        break
print("found 2 odd numbers")

5
7
found 2 odd numbers


In [85]:
count = 1
while(count <=10) :
    print("hello world")
    count = count + 1 

hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world
hello world


In [86]:
count = 1
while(count <=10) :
    print("hello world")
    count = count + 2 

hello world
hello world
hello world
hello world
hello world


In [7]:
i=1
count=0
while(i>0):
    if(i%2!=0):
        print(i)
        i=i+1
        count=count+1
        if(count==10):
            break
    else:
        i=i+1
         


1
3
5
7
9
11
13
15
17
19


In [15]:
list1=["Hello","12","exit","56"]
i=0
while(True):
    msg=list1[i]
    i=i+1
    if(msg.find("exit")>=0):
        break
    else:
        print(msg)

Hello
12


In [4]:
i=1
j=1
sum=0
while(i>0):
    if(j==50):
        break
    sum=sum+i
    i=i+1
    j=j+1
        
print(sum)

1225


In [1]:
i=555
j=0
while(i<1112):
    if(i%7==0):
        j=j+1
    i=i+1
print(j)      

79


In [3]:
i=1
j=0
sum=0
while(i<=10):
    sum=sum+(i**2)
    i=i+1
    
print(sum)
    

385


In [12]:
i=334
sum=0
while(i<=667):
    if(i%2==0):
        sum=sum+(i**2)
    i=i+1
print(sum)
    

43302432


In [13]:
i=555
sum=0
while(i<1112):
    if(i%7==0):
        sum=sum+i
    i=i+1
print(sum) 

65807


In [14]:
count=0            #Program to find 2 odd number from the list
myl=[1,2,3,4,5,6,7,8]
for i in range(len(myl)):
    j=int(i)
    k=myl[-(j+1)]
    if k%2!=0:
        print(k)
        count=count+1
    if count==2:
        break
print("End")

7
5
End


In [57]:
dict1={"key1":1,"key2":2,"key3":3}
for key,val in dict1.items():
        maxi=max(dict1)
print(maxi) #prints the key with max value
#print(key,val)

key3


In [24]:
list1=[10,22,30,14,15,6]
list1.sort()
print(list1)
print("Max:",list1[len(list1)-1])
print("Min:",list1[0])
s=0
for i in list1:
    s=s+i

print("Sum:",s)
    

[6, 10, 14, 15, 22, 30]
Max: 30
Min: 6
Sum: 97


In [26]:
i=input("Enter the number:")
k=i[::-1]
if(i==k):
    print("Palindrome")
else:
    print("Not Palindrome")

Enter the numberabcdcba
Palindrome


In [32]:
fact=int(input("Enter the Number"))
f=1
for i in range(fact+1):
    if (i!=0):
        f=f*i
print("Factorial of ",fact,"=",f)

Enter the Number8
Factorial of  8 = 40320


In [7]:
l=int(input("Enter Limit:"))
a=0
b=1
print(a)
print(b)
for i in range(l-2):
    c=a+b
    a=b
    b=c
    print(c)
    l=l-2
    
    
    

Enter Limit:5
0
1
1
2
3


In [ ]:
l=input("Enter the number:")
sum=0
for i in range(len(l)):
        sum=sum+(int(l[i])**3)
if sum==int(l):
    print(l,"is Armstrong")
else:
    print(l,"is not Armstrong")


In [8]:
l=input("Enter the number:")
print(l)
print(type(l))
l1=l.split(" ")
print(l1)
print(type(l1))
for i in l1:
    if(i.isdigit()):
        print("%d isdigit"%int(i))

Enter the number:1 hygh 5
1 hygh 5
<class 'str'>
['1', 'hygh', '5']
<class 'list'>
1 isdigit
5 isdigit


In [40]:
tup=(0,1,2,3,5,10) # Tuple only has two member function count and index
print(tup.count(0))
print(tup.index(5))

1
4


In [43]:
def isiteven(val):                    #Function
    if(val%2==0):
        return True
    else:
        return False

l=int(input("Enter the number:"))

result=isiteven(l)
print(result)


    
    

Enter the number:2
True


In [45]:
def maximum(l1):
    l1.sort()
    return  l1[len(l1)-1]

l=[1,8,93,4,56]
result=maximum(l)
print(result)


93


In [46]:
n=0b00001111
print(n)

15


In [50]:
l1=[1,2,3]
dir(l1)  # show all member functions of list

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [51]:
a=10
print(float(a))

10.0


In [94]:
dict1={"Name":"jithin", "Marks":{"Eng":80,"Maths":90,"Social":95}} # to find maximum value from a dictionary
l1=[]
l2=[]
for i,j in dict1["Marks"].items():
    l1.append(i)                         # Key
    l2.append(j)                        #Value
k=max(l2)
print(k)
index=l2.index(k)
print(l1[index])

95
Social


In [63]:
l1=[1,2,3,4,5,6]
l1.insert(2,"hello")
print(l1)


[1, 2, 'hello', 3, 4, 5, 6]


In [7]:
s=[1,2,3,4,5,6]         #iterator
a=iter(s)
count=0
a=iter(s)
b=next(a)
print(b)
b=next(a)
print(b)
'''
while count<6:
    e=next(a)
    print(e)
    count=count+1
''' 

1
2


'\nwhile count<6:\n    e=next(a)\n    print(e)\n    count=count+1\n'

In [14]:
s=[1,2,3,4,5,6]  
r=reversed(s)
print(next(r))


6


In [22]:
l1=[]
l2=[]
def fun(a):
    l2=a.split(" ")
    for i in l2:
        if i.isdigit():
             l1.append(i)
    return l1
a="20 is less than 30 but greater than 11"
#print(a.split(" "))
print(fun(a))

['20', '30', '11']


In [24]:
def fun1(a):
    for i in a:
        if i%2==0:
            r=i
            break
    return r       
a=[1,3,6,8,10,17]
print(fun1(a))


6


In [25]:
fun1=lambda a,b:a+b
print(fun1(2,3))

5


In [33]:
fun3=lambda a : True if a%2!=0 else False
n=int(input("Enter a Number:"))
print(fun3(n))

Enter a Number:1
True


In [34]:
def fun1(a):
    return a*2
list1=[1,2,3,4,5]                 
list2=list(map(fun1,list1))
print(list2)

[2, 4, 6, 8, 10]


In [35]:
def fun1(a):
    return a*2
tup1=(1,2,3,4,5)             
tup2=tuple(map(fun1,tup1))
print(list2)

[2, 4, 6, 8, 10]


In [37]:
def fun1(a):
    print(a*2)
list1=[1,2,3,4,5]                 
list2=map(fun1,list1) #won't be executed
print(list2)

In [38]:
def fun1(a):
    if a%2==0:
        return True
    else:
        return False
list1=[1,2,3,4,5]                 
list2=list(map(fun1,list1))
print(list2)

[False, True, False, True, False]


In [39]:
fun1=lambda a: True if a%2==0 else False
list1=[1,2,3,4,5]                 
list2=list(map(fun1,list1))
print(list2)

[False, True, False, True, False]


In [10]:
def fun1(a):
    return a*2
tup1=(1,2,3,4,5)             
tup2=tuple(filter(fun1,tup1))
print(tup2)

(1, 2, 3, 4, 5)


In [42]:
def fun1(a):
    if a%2==0:
        return True
    else:
        return False
list1=[1,2,3,4,5]                 
list2=list(filter(fun1,list1))
print(list2)

[2, 4]


In [49]:
def fun1(str1):
    if str1.isdigit():
        return True
    else: 
        return False
str1="Tv 10000 wm 20000"
list1=list(str1.split(" "))
list2=list(filter(fun1,list1))
print(list2)

['10000', '20000']


In [50]:
fun1=lambda a: True if a%2==0 else False
list1=[1,2,3,4,5]                 
list2=list(filter(fun1,list1))
print(list2)

[2, 4]


In [51]:
fun1=lambda a:a.isdigit()
str1="Tv 10000 wm 20000"
list1=list(str1.split(" "))
list2=list(filter(fun1,list1))
print(list2)

['10000', '20000']


In [11]:
list1=['1','2'] 
[list1[i] + list1[i+1] for i in range(0, len(list1), 2)]


['12']

In [33]:
def funa(a):
    funb(a.split(" "))
    
def funb(b):
    l1=list()
    for i in b:
        if i.isdigit():l1.append(i)
        else:
            a=func(i)
            if(a!= None):
                l1.append(a) 
    fund(l1)
    
def func(c):
    l2=list()
    k=0
    for i in c:
            if i.isdigit():
                k=k+1
                l2.extend(i)
    if(k!=0):       
        return "".join(l2)

def fund(d): 
        print(d)
  
funa("She is in her 40's but behaves as if she is a teenager who is 16!")

['40', '16']


In [1]:
from functools import reduce
result= reduce((lambda a:a.isdigit()),list1)
list1=["Hl",'1','2','3',"qwer"]
print(result)

NameError: name 'list1' is not defined

In [121]:
list1=["Hello","1","2","3","4"]
result=reduce(lambda x,y : int(x)+int(y), list(filter(lambda x : x.isdigit(),list1)))
print(result)

10


In [120]:
list1=["Hello","1","2","3","4"]
print(list(filter(lambda x : x.isdigit(),list1)))

list1=["Hello","1","2","3","4"]
result=reduce(lambda x,y : int(x)+int(y), filter(lambda x : x.isdigit(),list1))
print(result)

['1', '2', '3', '4']
10


In [117]:
from collections import Counter
from itertools import groupby

l = [1,2,3,3,3,4,4,4,5,5,6,6,6]

# group most_common output by frequency
freqs = groupby(Counter(l).most_common(), lambda x:x[1])
# pick off the first group (highest frequency)
print([val for val,count in next(freqs)[1]])
# prints [3, 4, 6]

[3, 4, 6]


In [125]:
import numpy 
ar=numpy.array([1,23,4,5,6])
print(ar)

[ 1 23  4  5  6]


In [ ]:
import numpy as np
ar=np.array([1,23,4,5,6])
print(ar)

In [129]:
list1=[1,2,3]
list2=[3,4,5]
print(list1+list2)

[1, 2, 3, 3, 4, 5]


In [131]:
import numpy as np
ar1=np.array([1,2,3])   # Matrices should be of the same size
ar2=np.array([4,5,6])
print(ar1*ar2)

[ 4 10 18]


In [134]:
import numpy as np
ar1=np.array([[1,2,3],[6,4,1],[2,4,5]])   # Matrices should be of the same size
ar2=np.array([[4,5,6],[9,4,6],[2,5,8]])
print(np.dot(ar1,ar2))

print(np.matmul(ar1,ar2))

[[28 28 42]
 [62 51 68]
 [54 51 76]]
[[28 28 42]
 [62 51 68]
 [54 51 76]]


In [136]:
import numpy as np
l1=[[1,2,3],[6,4,1],[2,4,5]]
l2=[[4,5,6],[9,4,6],[2,5,8]]
ar1=np.array(l1)   # Matrices should be of the same size
ar2=np.array(l2)
print(np.dot(ar1,ar2))

print(np.matmul(ar1,ar2))

[[28 28 42]
 [62 51 68]
 [54 51 76]]
[[28 28 42]
 [62 51 68]
 [54 51 76]]


In [137]:
import sys 
l1=list(range(1000))
t=sys.getsizeof(l1[0]*len(l1))
print(t)

24


In [146]:
import numpy as np
ar=np.arange(100)
print(ar)
ar.size  #no of elements in the array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


100

In [5]:
l1=[1,2,3,4,5] #to print prime numbers
l2=list(filter(lambda x : not x%2,l1))
print(l2)

[2, 4]


In [13]:
def findNextCellToFill(grid, i, j):
            for x in range(0,4):
                    for y in range(0,4):
                            if grid[x][y] == 0:
                                    return x,y 
            '''for x in range(i,4):
                    for y in range(j,4):
                            if grid[x][y] == 0:
                                    return x,y   
                                              '''
            return -1,-1

def isValid(grid, i, j, e):
            rowOk = all([e != grid[i][x] for x in range(4)])
            if rowOk:
                    columnOk = all([e != grid[x][j] for x in range(4)])
                    if columnOk:
                            # finding the top left x,y co-ordinates of the section containing the i,j cell
                            secTopX, secTopY = 2 *(i//2), 2 *(j//2) #floored quotient should be used here. 
                            for x in range(secTopX, secTopX+2):
                                    for y in range(secTopY, secTopY+2):
                                            if grid[x][y] == e:
                                                    return False
                            return True
            return False
        
def solveSudoku(grid, i=0, j=0):
            i,j = findNextCellToFill(grid, i, j)
            if i==-1:
                return True
            for val in range(1,5):
                if isValid(grid,i,j,val):
                    grid[i][j]=val   
                    if solveSudoku(grid, i, j):
                        return True
                    grid[i][j] = 0
            return False
        
        
input1=[[0,4,0,1],[3,0,4,0],[1,0,0,4],[0,2,1,0]]
solveSudoku(input1)
print(input1)


[[2, 4, 3, 1], [3, 1, 4, 2], [1, 3, 2, 4], [4, 2, 1, 3]]


In [14]:
def findNextCellToFill(grid, i, j):
            for x in range(i,9):
                    for y in range(j,9):
                            if grid[x][y] == 0:
                                    return x,y
            for x in range(0,9):
                    for y in range(0,9):
                            if grid[x][y] == 0:
                                    return x,y
            return -1,-1

def isValid(grid, i, j, e):
            rowOk = all([e != grid[i][x] for x in range(9)])
            if rowOk:
                    columnOk = all([e != grid[x][j] for x in range(9)])
                    if columnOk:
                            # finding the top left x,y co-ordinates of the section containing the i,j cell
                            secTopX, secTopY = 3 *(i//3), 3 *(j//3) #floored quotient should be used here. 
                            for x in range(secTopX, secTopX+3):
                                    for y in range(secTopY, secTopY+3):
                                            if grid[x][y] == e:
                                                    return False
                            return True
            return False
        
def solveSudoku(grid, i=0, j=0):
            i,j = findNextCellToFill(grid, i, j)
            if i == -1:
                    return True
            for e in range(1,10):
                    if isValid(grid,i,j,e):
                            grid[i][j] = e
                            if solveSudoku(grid, i, j):
                                    return True
                            # Undo the current cell for backtracking
                            grid[i][j] = 0
            return False
        
        
input1=[[3,0,6,5,0,8,4,0,0], 
[5,2,0,0,0,0,0,0,0], 
[0,8,7,0,0,0,0,3,1], 
[0,0,3,0,1,0,0,8,0], 
[9,0,0,8,6,3,0,0,5], 
[0,5,0,0,9,0,6,0,0], 
[1,3,0,0,0,0,2,5,0], 
[0,0,0,0,0,0,0,7,4], 
[0,0,5,2,0,6,3,0,0]] 

solveSudoku(input1)
print(input1)


[[3, 1, 6, 5, 7, 8, 4, 9, 2], [5, 2, 9, 1, 3, 4, 7, 6, 8], [4, 8, 7, 6, 2, 9, 5, 3, 1], [2, 6, 3, 4, 1, 5, 9, 8, 7], [9, 7, 4, 8, 6, 3, 1, 2, 5], [8, 5, 1, 7, 9, 2, 6, 4, 3], [1, 3, 8, 9, 4, 7, 2, 5, 6], [6, 9, 2, 3, 5, 1, 8, 7, 4], [7, 4, 5, 2, 8, 6, 3, 1, 9]]


In [26]:
import numpy as np
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [28]:

from numpy import array
from numpy import reshape
# define array
data = array([11, 22, 33, 44, 55])
print(data.shape)
# reshape
data = data.reshape((data.shape[0], 1))
print(data.shape)
print(data)

(5,)
(5, 1)
[[11]
 [22]
 [33]
 [44]
 [55]]


In [29]:

data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]


In [30]:
def print_factors(x):
   # This function takes a number and prints the factors

   print("The factors of",x,"are:")
   for i in range(1, x + 1):
       if x % i == 0:
           print(i)

# change this value for a different result.
num = 320

# uncomment the following line to take input from the user
#num = int(input("Enter a number: "))

print_factors(num)

The factors of 320 are:
1
2
4
5
8
10
16
20
32
40
64
80
160
320
